#!/usr/bin/perl
#
# Configure a linux distribution to connect to UCL's Eduroam wireless network
# This should work for Raspbian 9 (Stretch) and Raspbian 8 (Jessie)  
# This has been tested on:
#  Raspberry Pi 3b+  running Raspbian 9 (Stretch)
# Requires:
#  perl
#  iconv
#  openssl
# v2.0 Lee Heagney, 11/03/19
##############################################################################
my $wpa_dir     = "/etc/wpa_supplicant";
my $wpa_file    = "";
my $ssid        = "eduroam";
my $proto       = "RSN";
my $key_mgmt    = "WPA-EAP";
my $pairwise    = "CCMP";
my $auth_alg    = "OPEN";
my $eap         = "PEAP";
my $phase1      = "\"peaplabel=0\"";
my $phase2      = "\"auth=MSCHAPV2\"";
my $priority    = 1;
my $id          = "";
my $passwd      = "";
my $passwd_hash = "";
my $rasp_ver    = Detect_Raspbian_Version();

#################################################################################
# Detect version of Raspbian and deteremine which wpa_supplicant file to write to
#################################################################################

if ($rasp_ver eq "9") {
  ##################
  # Detected Stretch
  ##################
  $wpa_file = "$wpa_dir/wpa_supplicant-wlan0.conf";
} elsif ($rasp_ver eq "8") {
  #################
  # Detected Jessie
  #################
  $wpa_file = "$wpa_dir/wpa_supplicant.conf";
} else {
  die "Unable to detect which version of Raspbian we have installed!\n\n";
}

print "[$wpa_file]\n";

##############
# Print Header
##############
print "\n";
print "-----------------------------------------------------------\n";
print " Configuring access to UCL's Eduroam\n\n";
print " This will overwrite any settings you currently have in:\n\n";
print "  $wpa_file\n\n";
print " Please backup this file if you want to keep these settings\n";
print "-----------------------------------------------------------\n\n";

################################################
# Check if we are running as root, or under sudo
################################################
if ($> != 0) {
  Error("This script needs to be run as ROOT, or with 'sudo'\n\ni.e. sudo $0");
}

################
# Get UCL userid
################
print "Please enter your UCL userid: ";
chomp($id = <STDIN>);

##################################################################
# Check to see if we have a userid and it is in the correct format
##################################################################
if ($id eq "") {
  Error("You must enter your UCL userid");
} elsif ($id !~ /\@ucl/) {
  $id .= "\@ucl.ac.uk";
}

################################
# Get UCL password from end user
################################
print "Please enter your UCL password: ";
system("stty -echo");
chomp($passwd = <STDIN>);
system("stty echo");
print "\nPlease enter your UCL password again: ";
system("stty -echo");
chomp($passwd_again = <STDIN>);
system("stty echo");

#############################################
# Check to see if the entered passwords match
#############################################
if ($passwd eq $passwd_again) {
  if ($passwd eq "") {
    Error("You must enter your UCL password");
  } else {
    chomp(my $passwd_hash_full = `echo -n "$passwd" | iconv -t utf16le | openssl md4`);
    $passwd_hash = (split(/ /,$passwd_hash_full))[1];
  }
  #############################
  # Open WPA file to write data
  #############################
  open(FILE,"> $wpa_file") or Error("Unable to open WPA file for writing: $!\nMake sure you run this script as ROOT or with sudo\n\n i.e sudo $0\n");
  print FILE "ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev\n";
  print FILE "update_config=1\n";
  print FILE "country=GB\n\n";
  print FILE "network={\n";
  print FILE "\tssid=\"$ssid\"\n";
  print FILE "\tproto=$proto\n";
  print FILE "\tkey_mgmt=$key_mgmt\n";
  print FILE "\tpairwise=$pairwise\n"; 
  print FILE "\tauth_alg=$auth_alg\n";
  print FILE "\teap=$eap\n";
  print FILE "\tidentity=\"$id\"\n";
  print FILE "\tpassword=hash:$passwd_hash\n";
  print FILE "\tphase1=$phase1\n";
  print FILE "\tphase2=$phase2\n";
  print FILE "\tpriority=$priority\n";
  print FILE "}\n";
  close(FILE);
  print "\n\nConfiguration has been written to $wpa_file\n\n";
  print "Reboot and you should connect automatically to Eduroam\n\n";
  print "When your password expires you will need to run this script again\n\n";
  ###########################
  # Clean up before we finish
  ###########################
  CleanUp();
} else {
  Error("Passwords do not match");
}

###############
# Display Error
###############
sub Error {
 my $_error = shift;
 print "\n\nERROR: $_error\n\n";
 CleanUp();
 exit 1;
}

#############################################################
# Cleanup up history to remove any traces of the UCL Password
#############################################################
sub CleanUp {
 system("history -w");
 system("history -c");
}

#########################
# Detect Raspbian Version
#########################
sub Detect_Raspbian_Version {
 my $full_version = `cat /etc/debian_version`;
 chomp($full_version);
 my ($major,$minor) = split(/\./,$full_version);
 print "Full = $full_version ($major => $minor)\n";
 return($major);
}
